services:
  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Do not mount local node_modules
    env_file:
      - ./.env

  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Do not mount local node_modules
    env_file:
      - ./.env
